### ISSUE TITLE
20 Minutes into the Future with Google Cardboard and JavaScript

### ISSUE THREAD

**Issue by omgmog** [jsoxford/events#1]
A look at the technology we've got available to create Google Cardboard experiences using JavaScript.

![](https://camo.githubusercontent.com/fda80d59a84bc19a67aaca035ecd1838e7b3c4f9/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f64354d367830764b374b6d6e6d2f67697068792e676966)

**Comment by omgmog** [comment]
This will be different to the last attempt -- the slides and demos will not be as intertwined, but it will be more awesome.

If you missed the talk last time, you can find it here: http://www.tubechop.com/watch/7010590

**Comment by benfoxall** [comment]
@omgmog Yo, was chatting to @spikeheap about this - with the new venue, do you want to have a run through to test out the wifi/space etc?  We might be able to head there on an evening/weekend before if so

**Comment by omgmog** [comment]
I need to finalise my demos before I can confirm the requirements, so I'll let you know in a week or two.

Currently the plan is:
- have the slides, independent of the demos
- have demos available that people will be able to play with (providing all of the cardboard units I've ordered arrive!)

I think the commotion of getting everyone to use their phones in cardboards, while I'm presenting will detract from the talk, so still thinking of a way to bring it all together... such as a fun hour or so of assembling them at some point before.

If we can get an idea of the number of rows/columns of chairs, and a way to distribute the 30 cardboard kits amongst those, that would be a good start!

**Comment by benfoxall** [comment]
Cool.  Having demo-free slides might be a good shout.

I definitely agree that people constructing them would detract from your demo - building my cardboard took quite a while, and stuff like that is even slower when you are doing it as a group.  How about you hand out the kits as people arrive to stagger it a bit? Also, the venue has an area at the side where people could go to construct them I guess (is it hard to put it together without a table?).

![img_20151014_130029](https://cloud.githubusercontent.com/assets/51385/10633769/df55bcd4-77e4-11e5-8cba-a2cdda1b49c3.jpg)
![img_20151014_130035](https://cloud.githubusercontent.com/assets/51385/10633768/df53d360-77e4-11e5-8f04-50d5558241d0.jpg)

It'll depend on numbers, but we'll have several rows of chairs (as in the picture), and some higher stools around the back if we need more seats.

**Comment by omgmog** [comment]
Looks like a cool space, I'm leaning more towards not having a huge people-involved-demo, so the arrangement won't matter.

Will just have an informational talk, show off some cool things, and then invite people to look at the demos in their own time, using the cardboard units that I'll provide.

They arrived yesterday, and they're pretty nice for Cardboard v1.0 units...

![img_20151026_105325](https://cloud.githubusercontent.com/assets/50949/10753608/257f884e-7c8a-11e5-88a3-ff2a6db976d3.jpg)

As for constructing them, you can probably see that they're individually wrapped -- I might do the boring job of removing the extra bits of card, and sticking velcro in the right places, so they can be assembled in a snap.

Also as 123-reg are offering .xyz domains for 99p, I now have jscard.xyz to host demos and stuff :rocket:

**Comment by AverageMarcus** [comment]
@omgmog I'd be happy to come early and help assemble some if you want

**Comment by omgmog** [comment]
This went pretty well!

![](https://media.giphy.com/media/eoxomXXVL2S0E/giphy.gif)
