### ISSUE TITLE
Plenty of Free Parking for Ladas at the Bazaar

### ISSUE THREAD

**Issue by lpmi-13** [jsoxford/events#6]
Using the paradigm of Cathedrals vs Bazaars, this talk will focus on the current state of language learning applications and how they tackle the problem by creating a few complex things (Ferraris) when a focus on creating lots of simple combinable things (Ladas) might be better.

As an example, the task of "writing a research article" is similar to "creating a website" in that they are both very easy to state, but much more complex to actually carry out, with a large subset of mini-tasks requiring competency before the larger task can be accomplished well.

This will mostly be a big picture/inspirational talk with a call to arms for all interested!

**Comment by spikeheap** [comment]
:+1: :boom: :+1: How are you fixed for the 16th March?

**Comment by lpmi-13** [comment]
sounds good! Should definitely have at least one working demo by then

**Comment by spikeheap** [comment]
Great! If you want more time then we could shoot for the 18th of May?

**Comment by lpmi-13** [comment]
16th March suits me perfectly!

**Comment by spikeheap** [comment]
Awesome, you're in: https://github.com/jsoxford/jsoxford.github.com/issues/181
