### ISSUE TITLE
Full stack minus CSS - How CSS is slowly killing your users.

### ISSUE THREAD

**Issue by ISNIT0** [jsoxford/events#7]
We all have strong opinions on CSS, whether good or bad.

CSS can be really helpful, but if you don't think about how it works before writing selectors, you can seriously harm the performance of your page.

We will take a look at browser implementations of CSS selectors and what that means for your CSS.

Talk based on/inspired by: https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Writing_efficient_CSS

Probably will be a short rant.

**Comment by spikeheap** [comment]
Hey Joe, I'm a big fan of rants :). How does the 16th of March fit for you (https://github.com/jsoxford/jsoxford.github.com/issues/181)?

**Comment by ISNIT0** [comment]
@spikeheap Looks good to me!

**Comment by spikeheap** [comment]
Ace, I've added it in. Cheers!
